# Permalinks
permalink:        pretty

# Setup
url:              http://xesam.github.io/

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            Xesam

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  靠谱的娱乐型程序员

# The tags listed as entries in the sidebar
sidebar_tags:     [java, android, javascript, 计算机, 杂谈]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/nap.jpg
color:            '#A85641'

author:
  name:           'xesam'

  # Setting social media usernames will add icons at the bottom of the sidebar
  github:         xesam

  # Setting a disqus username will enable the comment section
  # disqus:         qwtel

  # This photo will be used in the about section
  photo:          https://avatars0.githubusercontent.com/u/1892804?v=3&s=460

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm [xesam](https://github.com/xesam)

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
